#!/usr/bin/bash
# .ignore


# THIS FILE IS AUTO GENERATED. YOU MAY RENAME AS YOU PLEASE.
# 
# This file will not be included when you build your project,
# so it is not recommended to add code to this.
#
# This file is for calling your script correctly. You must
# call your script from this directory, with this
#
# './multiline-text'
#
# command.
#
# If you are new to building with Shuttle please read
# the documentation for more information.
# ('shuttle docs')

source ./src/main.bash "$@"
